name: Update All Rulesets Separately
 Check failure on line 1 in .github/workflows/update-rules.yml


GitHub Actions
/ .github/workflows/update-rules.yml
Invalid workflow file

(Line: 69, Col: 1): 'on' is already defined, (Line: 74, Col: 1): 'jobs' is already defined, (Line: 135, Col: 1): 'on' is already defined, (Line: 140, Col: 1): 'jobs' is already defined

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
